#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
#
# @author: Lothar Rubusch
# @email: L.Rubusch@gmx.ch
# @license: GPLv3
# @2014-Feb-28

# implementation of a linear feedback shift register (LFSR) example,
# this may work as a PRNG, practically implementated by Flip-Flops


def die(msg):
    if 0 < len(msg): print msg
    sys.exit(1)


## increments a single bit, returns val and carry
#def bincrmeent(val):
#TODO


# list of feedback coeffs for encrypt / decrypt - this is generated by LFSR normally
feedback_coefficients = [] # TODO


## args - the filenmae
def main(argv=sys.argv[1:]):
    # TODO in case take plaintext as arg, 

### start ###
if __name__ == '__main__':
    main()
print "READY.\n"
